### ISSUE TITLE
Select is not selecting ng-model

### ISSUE THREAD

**Issue by cassio-rossi** [todaynowork/angular-northstar-ibm#3]
The <select> option is not been select when there is a ng-model. Here is my piece of code.

```
<select id="perfil" data-widget="selectlist" northstar-select ng-model="user.profile" data-placeholder="Selecione o Perfil">
	<option value="">Selecione o Perfil</option>
	<option ng-repeat="item in profiles" value ="{{item.id}}">{{item.description}}</option>
</select>

```
When I set something to user.profile, the select doesn't get that. The next time I open the overlay again, the selected option was the previous one - the one I selected manually.

**Comment by todaynowork** [comment]
fixed , please update from master and try again. Thanks a lot for your report

**Comment by cassio-rossi** [comment]
Hi. The fixed didn't work.
There are 2 errors:
1) There is a }]); missing at the end of the file
2) Instead of using $select2.on("select2:close use $select2.on("close.select2
and instead of $select2.val(selVal).trigger('change, use $select2.val(selVal).trigger('change.select2

then will work.

Thanks because your fix gave the idea to test and the response.

**Comment by todaynowork** [comment]
thanks a lot for your feedback. 
I have updated, please tell if this work. I have tested code in my local machine and works fine. I am not sure why it did not work to you.

Thanks,
Du
